# Generated by Django 5.0 on 2023-12-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('privacy_policy', models.TextField(max_length=500)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='device_frant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(default=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMaker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_description', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('include_ads', models.BooleanField(default=True)),
                ('game_name', models.CharField(max_length=100)),
                ('game_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('game_type', models.CharField(choices=[('HTML', 'HTML '), ('Cloud', 'Cloud'), ('Native', 'Native')], default='HTML', max_length=10)),
                ('developer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game_app.developer')),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game_app.device_frant')),
            ],
        ),
    ]
